<a href="https://colab.research.google.com/github/np03cs4a240060-bit/Concepts-and-Technologies-of-AI/blob/main/Worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:

Question 1

In [ ]:
import numpy as np
arr_empty = np.empty((2,2))
print(arr_empty)


[[2.06682422e-315 0.00000000e+000]
 [2.08017376e-315 7.90505033e-323]]


Question2

In [ ]:
import numpy as np
b = np.ones((4,2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Question 3

In [ ]:
import numpy as np
c = np.full((3,3), 7)   # Example: fill with 7
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


Question 4

In [1]:
import numpy as np
given_arr = np.array([[2,3,4],[5,6,7]])
arr_zeros_like = np.zeros_like(given_arr)
print(arr_zeros_like)


[[0 0 0]
 [0 0 0]]


question5

In [ ]:
import numpy as np
given_arr = np.array([[2,3,4],[5,6,7]])
arr_ones_like = np.ones_like(given_arr)
print(arr_ones_like)


Question6

In [ ]:
import numpy as np
new_list = [1,2,3,4]
arr_from_list = np.array(new_list)
print(arr_from_list)


Problem 2

Question1

In [2]:
arr_range = np.arange(10, 50)
print(arr_range)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Question2

In [ ]:
arr_matrix = np.arange(9).reshape(3,3)
print(arr_matrix)


Question3

In [3]:
identity_mat = np.eye(3)
print(identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Question4

In [4]:
rand_arr = np.random.random(30)
print("Mean:", rand_arr.mean())

Mean: 0.6318447991500559


Question5

In [5]:
arr_10x10 = np.random.random((10,10))
print("Min value:", arr_10x10.min())
print("Max value:", arr_10x10.max())

Min value: 0.012201171102792174
Max value: 0.9863172499679611


Question6

In [6]:
arr_zero = np.zeros(10)
arr_zero[4] = 1  # 5th element is index 4
print(arr_zero)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Question7

In [7]:
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
print(reversed_arr)


[0 4 0 0 2 1]


Question8

In [8]:
border_arr = np.ones((6,6))
border_arr[1:-1, 1:-1] = 0
print(border_arr)


[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


Question9

In [ ]:
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


Problem 3

In [9]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])


In [ ]:
Question1

In [10]:
add_xy = x + y
print(add_xy)


[[ 6  8]
 [10 13]]


Question2

In [ ]:
sub_xy = x - y
print(sub_xy)


Question3

In [ ]:
mult_x = x * 3
print(mult_x)


Question4

In [ ]:
square_x = x ** 2
print(square_x)


Question 5

In [11]:
#a
dot_vw = np.dot(v, w)
print(dot_vw)

#b
dot_vx = np.dot(v, x)
print(dot_vx)

#c
dot_xy = np.dot(x, y)
print(dot_xy)


219
[39 68]
[[19 22]
 [50 58]]


Question6

In [13]:
concat_xy = np.concatenate((x, y), axis=0)    # row-wise (vertical)
print(concat_xy)

concat_vw = np.vstack((v, w))  # column-wise for 1D arrays
print(concat_vw)


[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


Question7

In [27]:
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print(concat_xv)
except Exception as e:
    print("Error:", e)


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem 4

In [26]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])


Question1

In [23]:
import numpy as np

A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print(identity_check)


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


Question2

In [21]:
import numpy as np

AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)


AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]


Question3

In [20]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)


AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]


Solving the linear equation

In [19]:
import numpy as np

# Coefficient matrix A
A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3,  1, -1]
])

# Constant matrix B
B = np.array([-1, -3, 9])

# Solving using Inverse Method: X = A^(-1) * B
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Solution using Inverse Method:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])

# Solving using np.linalg.solve (more efficient and recommended)
X_solve = np.linalg.solve(A, B)

print("\nSolution using np.linalg.solve():")
print("x =", X_solve[0])
print("y =", X_solve[1])
print("z =", X_solve[2])


Solution using Inverse Method:
x = 2.0
y = 1.0
z = -2.0

Solution using np.linalg.solve():
x = 2.0
y = 1.0000000000000002
z = -2.0
